"
I am a demo class created in the Spider-GitDemo2 package.
"
Class {
	#name : #SpiderGitDemo2Class,
	#superclass : #Object,
	#instVars : [
		'city',
		'contry'
	],
	#category : #'Spider-GitDemo2'
}

{ #category : #accessing }
SpiderGitDemo2Class >> city [
	^ city
]

{ #category : #accessing }
SpiderGitDemo2Class >> city: anObject [
	city := anObject
]

{ #category : #accessing }
SpiderGitDemo2Class >> contry [
	^ contry
]

{ #category : #accessing }
SpiderGitDemo2Class >> contry: anObject [
	contry := anObject
]
